### ISSUE TITLE
Query Regarding the Necessity of Using Both Detection and Classification Models

### ISSUE THREAD

**Issue by Nomiluks** [LynnHaDo/Checkbox-Detection#8]
Question:

I observed that the `DETECTION_MODEL` model is capable of providing us with both confidence scores and object locations. Additionally, it informs us about the class of the box, such as whether it's checked, unchecked, or blocked. Given this functionality, is it possible to solely rely on the `DETECTION_MODEL` model instead of incorporating the `CLASSIFICATION_MODEL` model?

Here are the detection model results:
`{'class': 'checked', 'conf': 0.75}`

**Comment by LynnHaDo** [comment]
Good point! The reason I added a classification layer was just to increase (if possible) the accuracy of the class predicted, due to our concern about the detection model's performance. Of course, I did not perform any formal analysis of the results to determine the necessity of the classification step, so I could not say for sure that this is necessary. If you happen to train a model, and are confident in its precision then great, you can surely skip this step 👍.

A little bit of background: we initially trained a classification model to classify single images of checkboxes like these,

![18_unchecked](https://github.com/LynnHaDo/Checkbox-Detection/assets/109055421/0c13dd92-614d-4cba-9aa8-317223e1f11d)
![2_checked](https://github.com/LynnHaDo/Checkbox-Detection/assets/109055421/164918ce-ba1f-4890-9ef7-32c63faee2df)

which did reduce our manual workload of preparing the data for copy-and-paste process. I thought it might be useful to share this model with the community, to make it somewhat easier to re-create better and more robust data sets.

Hope that helps!

**Comment by Nomiluks** [comment]
Cool. Thank you!
